import type { UnitCategory } from '../units';

export interface UnitAlias {
  category: UnitCategory;
  unit: string;
}

/** Maps a lowercase, trimmed phrase a user might type to the canonical {category, unit} our converter knows. */
export const UNIT_ALIASES: Record<string, UnitAlias> = {
  // Length
  m: { category: 'length', unit: 'meter' },
  meter: { category: 'length', unit: 'meter' },
  meters: { category: 'length', unit: 'meter' },
  metre: { category: 'length', unit: 'meter' },
  metres: { category: 'length', unit: 'meter' },
  km: { category: 'length', unit: 'kilometer' },
  kilometer: { category: 'length', unit: 'kilometer' },
  kilometers: { category: 'length', unit: 'kilometer' },
  kilometre: { category: 'length', unit: 'kilometer' },
  kilometres: { category: 'length', unit: 'kilometer' },
  cm: { category: 'length', unit: 'centimeter' },
  centimeter: { category: 'length', unit: 'centimeter' },
  centimeters: { category: 'length', unit: 'centimeter' },
  mm: { category: 'length', unit: 'millimeter' },
  millimeter: { category: 'length', unit: 'millimeter' },
  millimeters: { category: 'length', unit: 'millimeter' },
  mi: { category: 'length', unit: 'mile' },
  mile: { category: 'length', unit: 'mile' },
  miles: { category: 'length', unit: 'mile' },
  yd: { category: 'length', unit: 'yard' },
  yard: { category: 'length', unit: 'yard' },
  yards: { category: 'length', unit: 'yard' },
  ft: { category: 'length', unit: 'foot' },
  foot: { category: 'length', unit: 'foot' },
  feet: { category: 'length', unit: 'foot' },
  in: { category: 'length', unit: 'inch' },
  inch: { category: 'length', unit: 'inch' },
  inches: { category: 'length', unit: 'inch' },
  nmi: { category: 'length', unit: 'nauticalMile' },
  'nautical mile': { category: 'length', unit: 'nauticalMile' },
  'nautical miles': { category: 'length', unit: 'nauticalMile' },

  // Mass
  kg: { category: 'mass', unit: 'kilogram' },
  kilogram: { category: 'mass', unit: 'kilogram' },
  kilograms: { category: 'mass', unit: 'kilogram' },
  g: { category: 'mass', unit: 'gram' },
  gram: { category: 'mass', unit: 'gram' },
  grams: { category: 'mass', unit: 'gram' },
  mg: { category: 'mass', unit: 'milligram' },
  milligram: { category: 'mass', unit: 'milligram' },
  milligrams: { category: 'mass', unit: 'milligram' },
  t: { category: 'mass', unit: 'tonne' },
  tonne: { category: 'mass', unit: 'tonne' },
  tonnes: { category: 'mass', unit: 'tonne' },
  ton: { category: 'mass', unit: 'tonne' },
  tons: { category: 'mass', unit: 'tonne' },
  lb: { category: 'mass', unit: 'pound' },
  lbs: { category: 'mass', unit: 'pound' },
  pound: { category: 'mass', unit: 'pound' },
  pounds: { category: 'mass', unit: 'pound' },
  oz: { category: 'mass', unit: 'ounce' },
  ounce: { category: 'mass', unit: 'ounce' },
  ounces: { category: 'mass', unit: 'ounce' },
  st: { category: 'mass', unit: 'stone' },
  stone: { category: 'mass', unit: 'stone' },
  stones: { category: 'mass', unit: 'stone' },

  // Volume
  l: { category: 'volume', unit: 'liter' },
  liter: { category: 'volume', unit: 'liter' },
  liters: { category: 'volume', unit: 'liter' },
  litre: { category: 'volume', unit: 'liter' },
  litres: { category: 'volume', unit: 'liter' },
  ml: { category: 'volume', unit: 'milliliter' },
  milliliter: { category: 'volume', unit: 'milliliter' },
  milliliters: { category: 'volume', unit: 'milliliter' },
  'cubic meter': { category: 'volume', unit: 'cubicMeter' },
  'cubic meters': { category: 'volume', unit: 'cubicMeter' },
  gal: { category: 'volume', unit: 'gallonUS' },
  gallon: { category: 'volume', unit: 'gallonUS' },
  gallons: { category: 'volume', unit: 'gallonUS' },
  qt: { category: 'volume', unit: 'quartUS' },
  quart: { category: 'volume', unit: 'quartUS' },
  quarts: { category: 'volume', unit: 'quartUS' },
  pt: { category: 'volume', unit: 'pintUS' },
  pint: { category: 'volume', unit: 'pintUS' },
  pints: { category: 'volume', unit: 'pintUS' },
  cup: { category: 'volume', unit: 'cupUS' },
  cups: { category: 'volume', unit: 'cupUS' },
  'fl oz': { category: 'volume', unit: 'fluidOunceUS' },
  'fluid ounce': { category: 'volume', unit: 'fluidOunceUS' },
  'fluid ounces': { category: 'volume', unit: 'fluidOunceUS' },

  // Speed
  'm/s': { category: 'speed', unit: 'meterPerSecond' },
  mps: { category: 'speed', unit: 'meterPerSecond' },
  'km/h': { category: 'speed', unit: 'kilometerPerHour' },
  kph: { category: 'speed', unit: 'kilometerPerHour' },
  kmh: { category: 'speed', unit: 'kilometerPerHour' },
  mph: { category: 'speed', unit: 'milePerHour' },
  knot: { category: 'speed', unit: 'knot' },
  knots: { category: 'speed', unit: 'knot' },
  'ft/s': { category: 'speed', unit: 'footPerSecond' },
  fps: { category: 'speed', unit: 'footPerSecond' },

  // Data
  byte: { category: 'data', unit: 'byte' },
  bytes: { category: 'data', unit: 'byte' },
  bit: { category: 'data', unit: 'bit' },
  bits: { category: 'data', unit: 'bit' },
  kb: { category: 'data', unit: 'kilobyte' },
  kilobyte: { category: 'data', unit: 'kilobyte' },
  kilobytes: { category: 'data', unit: 'kilobyte' },
  mb: { category: 'data', unit: 'megabyte' },
  megabyte: { category: 'data', unit: 'megabyte' },
  megabytes: { category: 'data', unit: 'megabyte' },
  gb: { category: 'data', unit: 'gigabyte' },
  gigabyte: { category: 'data', unit: 'gigabyte' },
  gigabytes: { category: 'data', unit: 'gigabyte' },
  tb: { category: 'data', unit: 'terabyte' },
  terabyte: { category: 'data', unit: 'terabyte' },
  terabytes: { category: 'data', unit: 'terabyte' },

  // Time
  sec: { category: 'time', unit: 'second' },
  secs: { category: 'time', unit: 'second' },
  second: { category: 'time', unit: 'second' },
  seconds: { category: 'time', unit: 'second' },
  ms: { category: 'time', unit: 'millisecond' },
  millisecond: { category: 'time', unit: 'millisecond' },
  milliseconds: { category: 'time', unit: 'millisecond' },
  min: { category: 'time', unit: 'minute' },
  mins: { category: 'time', unit: 'minute' },
  minute: { category: 'time', unit: 'minute' },
  minutes: { category: 'time', unit: 'minute' },
  hr: { category: 'time', unit: 'hour' },
  hrs: { category: 'time', unit: 'hour' },
  hour: { category: 'time', unit: 'hour' },
  hours: { category: 'time', unit: 'hour' },
  day: { category: 'time', unit: 'day' },
  days: { category: 'time', unit: 'day' },
  week: { category: 'time', unit: 'week' },
  weeks: { category: 'time', unit: 'week' },
  year: { category: 'time', unit: 'year' },
  years: { category: 'time', unit: 'year' },

  // Temperature
  c: { category: 'temperature', unit: 'celsius' },
  celsius: { category: 'temperature', unit: 'celsius' },
  f: { category: 'temperature', unit: 'fahrenheit' },
  fahrenheit: { category: 'temperature', unit: 'fahrenheit' },
  k: { category: 'temperature', unit: 'kelvin' },
  kelvin: { category: 'temperature', unit: 'kelvin' },
};

export function resolveUnit(phrase: string): UnitAlias | null {
  const key = phrase.trim().toLowerCase();
  return UNIT_ALIASES[key] ?? null;
}
